package dataConnector;

/**
 * Handles which manager BrokerDatabase will return
 * @author Owner
 *
 */
public enum SelectManager {
	ATTACHMENT_MANAGER,
	CATEGORY_MANAGER,
	CUSTOM_MANAGER,
	IMPACT_MANAGER,
	PRIORITY_MANAGER,
	QUEUE_APPROVER_LABEL_JT_MANAGER,
	QUEUE_MANAGER,
	QUEUE_OWNER_LABEL_MANAGER,
	QUEUE_SUBMITTER_LABEL_JT_MANAGER,
	STATUS_MANAGER,
	TICKET_CHANGE_FIELD_MANAGER,
	TICKET_CHANGE_MANAGER,
	TICKET_MANAGER,
	TICKET_RELATED_MANAGER,
	USERS_MANAGER,
	WORK_MANAGER
}
